name: Daily Database Backup

on:
  schedule:
    # This runs at 00:00 UTC every day (Approx 9:00 PM in Uruguay/Argentina)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows you to run it manually anytime for testing

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run pg_dump
        env:
          DATABASE_URL: ${{ secrets.BACKUP_DATABASE_URL }}
        run: |
          # Creates a filename with the current date
          FILENAME="backup-$(date +'%Y-%m-%d_%H-%M').sql"
          pg_dump "$DATABASE_URL" --no-owner --no-acl --column-inserts > $FILENAME
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-backup-${{ env.FILENAME }}
          path: ${{ env.FILENAME }}
          retention-days: 7 # GitHub will delete old backups after 7 days to save space